### ISSUE TITLE
Client: Process second line of response(data block).

### ISSUE THREAD

**Issue by thelimeburner** [gwAdvNet2015/gw-kv-store#13]
We have successfully been able to read the first line of the server response by reading byte by byte. We now need to process the data block of the server response in order to finish. @jdk514 @kstats

**Comment by twood02** [comment]
In the next class you should coordinate with @nks5295 since he will be working on the portion of the server that reads in the strings sent by the client so they can be sent to a parser.  You both will be dealing with similar issues for reading in lines from a socket, so a few helper functions might be useful on both sides.

**Comment by twood02** [comment]
solved in #29.
